version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "America/Los_Angeles"
    labels:
      - "skip changelog"
      - "dependencies"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "America/Los_Angeles"
    labels:
      - "skip changelog"
      - "dependencies"
