name: 'Changie Action'
description: 'Run Changie commands as part of a GitHub action workflow'
author: 'miniscruff'
branding:
  color: 'purple'
  icon: 'file-text'

inputs:
  version:
    description: 'Changie version'
    default: 'latest'
    required: false
  args:
    description: 'Arguments to pass to Changie'
    required: true

outputs:
  output:
    description: 'Results of running the changie command'

runs:
  using: 'node16'
  main: 'dist/index.js'
