name: Generate release pull request

on:
  workflow_dispatch:

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - run: npm ci
    - run: npm run build

    - name: Batch changes
      uses: ./
      with:
        version: latest
        args: batch auto

    - name: Merge changes
      uses: ./
      with:
        version: latest
        args: merge

    - name: Get the latest version
      id: latest
      uses: ./
      with:
        version: latest
        args: latest

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Release ${{ steps.latest.outputs.output }}
        branch: release/${{ steps.latest.outputs.output }}
        commit-message: Release ${{ steps.latest.outputs.output }}
